### ISSUE TITLE
Failed to handle `null` value in seed data

### ISSUE THREAD

**Issue by IanBoyanZhang** [jianwu-github/mongoose-data-seeder#2] opened 2019-02-06 19:40 UTC
Thanks for your help. When using this tool, we encountered below error.

`falied to load data to MongoDB
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at MongooseDataSeeder.unwind (/xxx/node_modules/mongoose-data-seeder/index.js:150:19)
    at MongooseDataSeeder.parseValue (/xxx/node_modules/mongoose-data-seeder/index.js:117:19)
    at Object.keys.map.key (/xxx/node_modules/mongoose-data-seeder/index.js:152:29)
    at Array.map (<anonymous>)
    at MongooseDataSeeder.unwind (/xxx/node_modules/mongoose-data-seeder/index.js:151:8)
    at MongooseDataSeeder.<anonymous> (/xxx/node_modules/mongoose-data-seeder/index.js:242:34)
    at tasks.reduce (/xxx/node_modules/mongoose-data-seeder/index.js:51:20)
    at Array.reduce (<anonymous>)
    at MongooseDataSeeder.asyncSeries (/xxx/node_modules/mongoose-data-seeder/index.js:48:21)
    at Promise.resolve.then.then (/xxx/node_modules/mongoose-data-seeder/index.js:261:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
`

**Comment by jianwu-github** [comment] 2019-02-07 03:38
The problem is fixed with latest commit 9af542a and a new version 1.0.3 has been published to npmjs.com

**Closed by jianwu-github** 2019-02-07 03:38 UTC
